# This is the name of the workflow that will be displayed in the Actions Tab
name: CICD

# Manual Click (deliver) workflow whenever the user needs
on:
  workflow_dispatch: 
    inputs:
      environment:
        description: This is the environment value where the workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Code Clone from GitHub."
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
     - name: Build Docker Container
       run: echo "Docker Container build"
       
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test the Container
        run: echo "Testing the Container"
      
  deploy:
    if: ${{ inputs.environment == 'dev' }}
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "docker compose deploy the apps"
