# API Keys, Sensitive Data, Credntials etc.
# GitLeaks
name: Secrets Scan

on:
    workflow_call:

jobs:
     secrets-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0  # Fetch all history for accurate scanning

            - name: Run GitLeaks Scanner
              uses: gitleaks/gitleaks-action@v2
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub actions manages it
               # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations, not personal accounts.

        
     